apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.postgresql.baiju.dev
  annotations:
    servicebindingoperator.redhat.io/spec.dbName: 'binding:env:attribute'
    servicebindingoperator.redhat.io/status.dbCredentials.user: 'binding:env:object:secret'
    servicebindingoperator.redhat.io/status.dbCredentials.password: 'binding:env:object:secret'
    servicebindingoperator.redhat.io/status.dbConnectionIP: 'binding:env:attribute'
    servicebindingoperator.redhat.io/status.dbConnectionPort: 'binding:env:attribute'
    servicebindingoperator.redhat.io/status.dbName: 'binding:env:attribute'
    servicebindingoperator.redhat.io/status.dbConfigMap.db.host: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap.db.port: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap.db.name: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap.db.user: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap.db.password: 'binding:env:object:configmap'
spec:
  group: postgresql.baiju.dev
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
      - db
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
